#!/usr/bin/env bash
#                        transfused                       #
## Automates backing up and restoring Plasma user configs   #
#####                        no names                       #####
underline=`tput smul`
nounderline=`tput rmul`
HELP=$(echo " ";
       echo "#########################################################################";
       echo "#                                                                       #";
       echo "#   TRANSFUSED - a Script to Backup and Restore Plasma User Configs      #";
       echo "#                                                                       #";
       echo "#   transfused [option] [USER]                                #";
       echo "#                                                                       #";
       echo "#   options:                                                            #";
       echo "#   help, -h, --help                                  show brief help   #";
       echo "#   backup, -b, --backup USER                     backup USER configs   #";
       echo "#   backuptopical, -bt, --backupt USER         backup USER appearance   #";
       echo "#   backuproot, -BR, --backuproot                 backup root configs   #";
       echo "#   copy, -C, --copy USER                    copy but do not compress   #";
       echo "#   compress, -c, --compress                  compress copied configs   #";
       echo "#   restore, -r, --restore USER       restore configs /to/ USER   #";
       echo "#                                                                       #";
       echo "#                               ${underline}  NOTES  ${nounderline}                               #";
       echo "#   Environment Variable        CHARTS=1          More verbose output   #";
       echo "#   Environment Variable        COVERED=1       Forgo wallpaper steps   #";
       echo "#                                                                       #";
       echo "#########################################################################";
       echo " ";)
TIMESTAMP=$(date +"%Y%m%d_%H%M")
# We dont need no stinkin coppers.
if [ "$EUID" = 0 ];
  then echo -e "\n Do not run this script as root!\n";
  exit;
fi

if [ $# -eq 0 ]; 
  then echo "";
  while true; do
  PS3=$'\n'"Please enter your choice: "
  options=("Backup" "Copy" "Compress" "Restore" "Help" "Quit")
  COLUMNS=26
  select opt in "${options[@]}"
  do
      case "$opt,$REPLY" in
          Backup,*|*,[bB]ackup)
              echo ""
              read -p "Please enter the name of the user to backup and compress configs from: "  USR
              "$0" -b "$USR";
              break
              ;;
          Copy,*|*,[cC]opy)
              echo ""
              read -p "Please enter the name of the user to copy configs from: "  USR
              "$0" -C "$USR";
              break
              ;;
          Compress,*|*,[cC]ompress)
              "$0" -c;
              break
              ;;
          Restore,*|*,[rR]estore)
              echo ""
              read -p "Please enter the name of the user to restore configs to: "  USR
              "$0" -r "$USR";
              break
              ;;
          Help,*|*,[hH]elp)
              "$0" -h;
              break
              ;;             
          Quit,*|*,[qQ]uit)
              break 2
              ;;
          *) echo "invalid option $REPLY";;
      esac
  done;
  done;
fi;

while test $# -gt 0; do

case "$1" in

-b|backup|--backup)

 shift
 if test $# -gt 0; then
 USR=`echo $1 | sed -e 's/^[^ ]* //g'`
  if [ ! -d "$HOME" ]; then
   echo -e "\n Directory $HOME does not exist\n";
   exit;
  fi;
 mkdir -p /tmp/"$USR"_transfusion_"$TIMESTAMP";
 mkdir -p /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config;
 mkdir -p /tmp/"$USR"_transfusion_"$TIMESTAMP"/.kde;
 mkdir -p /tmp/"$USR"_transfusion_"$TIMESTAMP"/.kde4;
 mkdir -p /tmp/"$USR"_transfusion_"$TIMESTAMP"/.local/share;
 rsync -rltD --ignore-missing-args $HOME/.config/auroraerc /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/autostart-scripts /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/autostart /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/breezerc /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/dolphinrc /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/gtk-3.0 /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/katemetainfos /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/katerc /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/kateschemarc /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/katevirc /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/kde.org /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/kdeconnect /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/kdeglobals /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/kglobalshortcutsrc /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/khotkeysrc /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/konsolerc /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/kscreenlockerrc /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/ksplashrc /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/kvantum /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/kwinrc /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/kwinrulesrc /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/latte /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/lattedockrc /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/plasma-org.kde.plasma.desktop-appletsrc /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/plasma-workspace /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/plasma_calendar_holiday_regions /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/plasmarc /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/plasmashellrc /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/powermanagementprofilesrc /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/pulse/*.conf /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/pulse/;
 rsync -rltD --ignore-missing-args $HOME/.config/qtcurve /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/Trolltech.conf /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.gtkrc-2.0 /tmp/"$USR"_transfusion_"$TIMESTAMP"/;
 rsync -rltD --ignore-missing-args $HOME/.kde /tmp/"$USR"_transfusion_"$TIMESTAMP"/;
 rsync -rltD --ignore-missing-args $HOME/.kde4 /tmp/"$USR"_transfusion_"$TIMESTAMP"/;
 rsync -rltD --ignore-missing-args $HOME/.local/share/aurorae /tmp/"$USR"_transfusion_"$TIMESTAMP"/.local/share/;
 rsync -rltD --ignore-missing-args $HOME/.local/share/color-schemes /tmp/"$USR"_transfusion_"$TIMESTAMP"/.local/share/;
 rsync -rltD --ignore-missing-args $HOME/.local/share/kate /tmp/"$USR"_transfusion_"$TIMESTAMP"/.local/share/;
 rsync -rltD --ignore-missing-args $HOME/.local/share/konsole /tmp/"$USR"_transfusion_"$TIMESTAMP"/.local/share/;
 rsync -rltD --ignore-missing-args $HOME/.local/share/kservices5 /tmp/"$USR"_transfusion_"$TIMESTAMP"/.local/share/;
 rsync -rltD --ignore-missing-args $HOME/.local/share/kxmlgui5/ /tmp/"$USR"_transfusion_"$TIMESTAMP"/.local/share/;
 rsync -rltD --ignore-missing-args $HOME/.local/share/plasma /tmp/"$USR"_transfusion_"$TIMESTAMP"/.local/share/;
 rsync -rltD --ignore-missing-args $HOME/.local/share/plasma_icons /tmp/"$USR"_transfusion_"$TIMESTAMP"/.local/share/;
  if [ -z "$COVERED" ]; then
   mkdir -p /tmp/"$USR"_transfusion_"$TIMESTAMP"/.local/share/wallpapers;
   OLDFLWR=$(awk -F: '/\[Wallpaper\]/ && $0 != "" { getline; print substr($0,14,length($0)-13) }' $HOME/.config/plasma-org.kde.plasma.desktop-appletsrc);
   AROSE=$(basename -- "$OLDFLWR");
   rsync -rltD --ignore-missing-args "$OLDFLWR" /tmp/"$USR"_transfusion_"$TIMESTAMP"/.local/share/wallpapers;
   mv /tmp/"$USR"_transfusion_"$TIMESTAMP"/.local/share/wallpapers/"$AROSE" /tmp/"$USR"_transfusion_"$TIMESTAMP"/.local/share/wallpapers/flowers;
   else
   echo -e '\n You are "Covered", meaning no wallpaper was copied.';
   echo -e 'That, or there was an error.';
  fi;
  if [[ $CHARTS -eq 1 ]]; 
   then
   tar -zcvf ./"$USR"_transfusion_"$TIMESTAMP".tar.gz /tmp/"$USR"_transfusion_"$TIMESTAMP";
   else 
   { 
   tar -zcvf ./"$USR"_transfusion_"$TIMESTAMP".tar.gz /tmp/"$USR"_transfusion_"$TIMESTAMP";
   } &> /dev/null;
  fi;
 rm -rf /tmp/"$USR"_transfusion_"$TIMESTAMP";
 echo -e "\nWe copied and compressed items recursively from:\n\n~\n~/.config\n~/.local/share\n\nThe compressed backup is timestamped and named "$USR"_transfusion_"$TIMESTAMP".tar.gz\n" ;
 else 
 echo -e "\n I dont know what to do";
 echo "$HELP";
 exit;
 fi;
 shift;; # backup and squish

-bt|backuptopical|--backupt)

 shift
 if test $# -gt 0; then
 USR=`echo $1 | sed -e 's/^[^ ]* //g'`
  if [ ! -d "$HOME" ]; then
   echo -e "\n Directory $HOME does not exist\n";
   exit;
  fi;
  mkdir -p /tmp/"$USR"_transfusion_"$TIMESTAMP";
  mkdir -p /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config;
  mkdir -p /tmp/"$USR"_transfusion_"$TIMESTAMP"/.kde;
  mkdir -p /tmp/"$USR"_transfusion_"$TIMESTAMP"/.local/share;
  rsync -rltD --ignore-missing-args $HOME/.config/auroraerc /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
  rsync -rltD --ignore-missing-args $HOME/.config/gtk-3.0 /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
  rsync -rltD --ignore-missing-args $HOME/.config/kdeglobals /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
  rsync -rltD --ignore-missing-args $HOME/.config/kscreenlockerrc /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
  rsync -rltD --ignore-missing-args $HOME/.config/ksplashrc /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
  rsync -rltD --ignore-missing-args $HOME/.config/kvantum /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
  rsync -rltD --ignore-missing-args $HOME/.config/kwinrc /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
  rsync -rltD --ignore-missing-args $HOME/.config/latte /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
  rsync -rltD --ignore-missing-args $HOME/.config/lattedockrc /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
  rsync -rltD --ignore-missing-args $HOME/.config/plasmarc /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
  rsync -rltD --ignore-missing-args $HOME/.config/qtcurve /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
  rsync -rltD --ignore-missing-args $HOME/.config/Trolltech.conf /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
  rsync -rltD --ignore-missing-args $HOME/.gtkrc-2.0 /tmp/"$USR"_transfusion_"$TIMESTAMP"/;
  rsync -rltD --ignore-missing-args $HOME/.kde /tmp/"$USR"_transfusion_"$TIMESTAMP"/;
  rsync -rltD --ignore-missing-args $HOME/.local/share/aurorae /tmp/"$USR"_transfusion_"$TIMESTAMP"/.local/share/;
  rsync -rltD --ignore-missing-args $HOME/.local/share/color-schemes /tmp/"$USR"_transfusion_"$TIMESTAMP"/.local/share/;
  rsync -rltD --ignore-missing-args $HOME/.local/share/konsole /tmp/"$USR"_transfusion_"$TIMESTAMP"/.local/share/;
  rsync -rltD --ignore-missing-args $HOME/.local/share/kxmlgui5/ /tmp/"$USR"_transfusion_"$TIMESTAMP"/.local/share/;
  rsync -rltD --ignore-missing-args $HOME/.local/share/plasma /tmp/"$USR"_transfusion_"$TIMESTAMP"/.local/share/;
  rsync -rltD --ignore-missing-args $HOME/.local/share/plasma_icons /tmp/"$USR"_transfusion_"$TIMESTAMP"/.local/share/;
  if [[ $CHARTS -eq 1 ]]; 
   then
   tar -zcvf ./"$USR"_transfusion_T-"$TIMESTAMP".tar.gz /tmp/"$USR"_transfusion_"$TIMESTAMP";
   else 
   { 
   tar -zcvf ./"$USR"_transfusion_T-"$TIMESTAMP".tar.gz /tmp/"$USR"_transfusion_"$TIMESTAMP";
   } &> /dev/null;
  fi;
 rm -rf /tmp/"$USR"_transfusion_"$TIMESTAMP";
 echo -e "\nWe copied and compressed items recursively from:\n\n~\n~/.config\n~/.local/share\n\nThe compressed backup is timestamped and named "$USR"_transfusion_T-"$TIMESTAMP".tar.gz" ;
 echo -e "\nThis is a 'topical' backup. Only the minimum of themes and aesthetics are saved.\n"
 else 
 echo -e "\n I dont know what to do";
 echo "$HELP";
 exit;
 fi;
 shift;; # backup and squish

-BR|backuproot|--backuproot)

 mkdir -p /tmp/root_transfusion_"$TIMESTAMP";
 mkdir -p /tmp/root_transfusion_"$TIMESTAMP"/usr/share;
 rsync -av --ignore-missing-args /usr/share/aurorae /tmp/root_transfusion_"$TIMESTAMP"/usr/share/;
 rsync -av --ignore-missing-args /usr/share/color-schemes /tmp/root_transfusion_"$TIMESTAMP"/usr/share/;
 rsync -av --ignore-missing-args /usr/share/icons /tmp/root_transfusion_"$TIMESTAMP"/usr/share/;
 rsync -av --ignore-missing-args /usr/share/kde-gtk-config /tmp/root_transfusion_"$TIMESTAMP"/usr/share/;
 rsync -av --ignore-missing-args /usr/share/kde4 /tmp/root_transfusion_"$TIMESTAMP"/usr/share/;
 rsync -av --ignore-missing-args /usr/share/konsole /tmp/root_transfusion_"$TIMESTAMP"/usr/share/;
 rsync -av --ignore-missing-args /usr/share/Kvantum /tmp/root_transfusion_"$TIMESTAMP"/usr/share/;
 rsync -av --ignore-missing-args /usr/share/plasma /tmp/root_transfusion_"$TIMESTAMP"/usr/share/;
 rsync -av --ignore-missing-args /usr/share/sddm /tmp/root_transfusion_"$TIMESTAMP"/usr/share/;
 rsync -av --ignore-missing-args /usr/share/themes /tmp/root_transfusion_"$TIMESTAMP"/usr/share/;
 rsync -av --ignore-missing-args /usr/share/wallpapers /tmp/root_transfusion_"$TIMESTAMP"/usr/share/;
  if [[ $CHARTS -eq 1 ]]; 
   then
   tar -zcvf ./root_transfusion_"$TIMESTAMP".tar.gz /tmp/root_transfusion_"$TIMESTAMP";
   else
   {
   tar -zcvf ./root_transfusion_"$TIMESTAMP".tar.gz /tmp/root_transfusion_"$TIMESTAMP";
   } &> /dev/null;
  fi;
 rm -rf /tmp/root_transfusion_"$TIMESTAMP";
 echo -e "\n\nWe copied and compressed items recursively from:\n\n/usr/share/\n\nThe compressed backup is named root_transfusion_"$TIMESTAMP".tar.gz\n";
 exit;; # backup and squish

-C|copy|--copy)

 shift
 if test $# -gt 0; then
 USR=`echo $1 | sed -e 's/^[^ ]* //g'`
  if [ ! -d "$HOME" ]; then
   echo -e "\n Directory $HOME does not exist\n";
   exit;
  fi;
 {
 mkdir -p /tmp/"$USR"_transfusion_"$TIMESTAMP";
 mkdir -p /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config;
 mkdir -p /tmp/"$USR"_transfusion_"$TIMESTAMP"/.kde;
 mkdir -p /tmp/"$USR"_transfusion_"$TIMESTAMP"/.kde4;
 mkdir -p /tmp/"$USR"_transfusion_"$TIMESTAMP"/.local/share;
 rsync -rltD --ignore-missing-args $HOME/.config/auroraerc /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/autostart-scripts /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/autostart /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/breezerc /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/dolphinrc /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/gtk-3.0 /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/katemetainfos /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/katerc /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/kateschemarc /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/katevirc /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/kde.org /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/kdeconnect /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/kdeglobals /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/kglobalshortcutsrc /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/khotkeysrc /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/konsolerc /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/kscreenlockerrc /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/ksplashrc /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/kvantum /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/kwinrc /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/kwinrulesrc /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/latte /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/lattedockrc /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/plasma-org.kde.plasma.desktop-appletsrc /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/plasma-workspace /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/plasma_calendar_holiday_regions /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/plasmarc /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/plasmashellrc /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/powermanagementprofilesrc /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/pulse/*.conf /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/pulse/;
 rsync -rltD --ignore-missing-args $HOME/.config/qtcurve /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.config/trolltech.conf /tmp/"$USR"_transfusion_"$TIMESTAMP"/.config/;
 rsync -rltD --ignore-missing-args $HOME/.gtkrc-2.0 /tmp/"$USR"_transfusion_"$TIMESTAMP"/;
 rsync -rltD --ignore-missing-args $HOME/.kde /tmp/"$USR"_transfusion_"$TIMESTAMP"/;
 rsync -rltD --ignore-missing-args $HOME/.kde4 /tmp/"$USR"_transfusion_"$TIMESTAMP"/;
 rsync -rltD --ignore-missing-args $HOME/.local/share/aurorae /tmp/"$USR"_transfusion_"$TIMESTAMP"/.local/share/;
 rsync -rltD --ignore-missing-args $HOME/.local/share/color-schemes /tmp/"$USR"_transfusion_"$TIMESTAMP"/.local/share/;
 rsync -rltD --ignore-missing-args $HOME/.local/share/kate /tmp/"$USR"_transfusion_"$TIMESTAMP"/.local/share/;
 rsync -rltD --ignore-missing-args $HOME/.local/share/konsole /tmp/"$USR"_transfusion_"$TIMESTAMP"/.local/share/;
 rsync -rltD --ignore-missing-args $HOME/.local/share/kservices5 /tmp/"$USR"_transfusion_"$TIMESTAMP"/.local/share/;
 rsync -rltD --ignore-missing-args $HOME/.local/share/kxmlgui5 /tmp/"$USR"_transfusion_"$TIMESTAMP"/.local/share/;
 rsync -rltD --ignore-missing-args $HOME/.local/share/plasma /tmp/"$USR"_transfusion_"$TIMESTAMP"/.local/share/;
 rsync -rltD --ignore-missing-args $HOME/.local/share/plasma_icons /tmp/"$USR"_transfusion_"$TIMESTAMP"/.local/share/;
 } &> /dev/null;
 echo -e "\n\nWe copied items recursively from:\n\n~\n~/.config\n~/.local/share\n\nThe new directory is timestamped and named "$USR"_transfusion_"$TIMESTAMP"\n" ;
 else
 echo -e "\n I dont know what to do";
 echo "$HELP";
 exit;
 fi;
 shift;; # make a folder but dont sit on it

-c|compress|--compress)

  echo " ";
  unset options i
  while IFS= read -r -d $'\0' f; do
    options[i++]="$f"
  done < <(find . -maxdepth 1 -type d -name "*_transfusion_*" -print0 )
   select opt in "${options[@]}" "Quit"; do
     case $opt in
       *_transfusion_*)
          if [[ $CHARTS -eq 1 ]]; 
           then
           tar -zcvf "${opt}.tar.gz" "$opt";
           else
           {
           tar -zcvf "${opt}.tar.gz" "$opt";
           } &> /dev/null;
          fi;
          echo -e "\nCompressed items recursively from:\n\n"$opt"\n";   
         break
         ;;
       "Quit")
         echo -e "\nYou chose to quit"
         break
         ;;
       *)
         echo "Invalid selection"
         ;;
     esac
   done
 exit;; # now you can sit on it 

-h|help|--help)

 echo "$HELP" ;
 exit;;

-r|restore|--restore)

 shift
 if test $# -gt 0; then
 unset options i
 while IFS= read -r -d $'\0' f; do
   options[i++]="$f"
 done < <(find . -maxdepth 1 -type f -name "*.tar.gz" -print0)
  select opt in "${options[@]}" "Quit"; do
    case $opt in
      *.tar.gz)
        echo -e "\nBackup file $opt selected";
        # processing
        break
        ;;
      "Quit")
        echo -e "\nYou chose to quit"
        break
        ;;
      *)
        echo "Invalid selection"
        ;;
    esac
  done
  USER=$(echo $1 | sed -e 's/^[^ ]* //g')
    if [ ! -d "/home/$USR" ]; then
     echo -e "\n Directory /home/$USR does not exist\n";
     exit;
    fi;
    if [ ! -f "$opt" ]; then
     echo -e "\n No Backup selected\n";
     exit;
    fi;
 echo " ";
 read -p "Are you sure you would like to restore "$opt" to /home/$USR/? (Y/N) " -n 1 -r ;
 echo " ";
  if [[ ! $REPLY =~ ^[Yy]$ ]];
   then exit 1;
  fi;
  if [ -z "$COVERED" ]; then
  sed -i '/Contain.*\[Wallpaper\]/!b;n;cImage=file:///home/'"$USR"'/.local/share/wallpapers/flowers' /home/"$USR"/.config/plasma-org.kde.plasma.desktop-appletsrc;
  else
  echo -e '\n You are "Covered", meaning no change will be made to configured wallpaper selection.';
  echo -e 'That, or there was an error.';
  fi; 
  if [[ $CHARTS -eq 1 ]]; 
   then
   mkdir -p /tmp/transfusion;
   tar -xzvf "$opt" -C /tmp/transfusion/;
   COPYF=/tmp/transfusion/${opt::-7}
   rsync -rltDii --ignore-missing-args $COPYF/ --include=".*" /home/$USR/;
   rm -rf "$COPYF" ;
   else
   {
   mkdir -p /tmp/transfusion;
   tar -xzvf "$opt" -C /tmp/transfusion;
   COPYF=/tmp/transfusion/${opt::-7}
   rsync -rltD --ignore-missing-args $COPYF/ --include=".*" /home/$USR/;
   rm -rf "$COPYF" ;
   } &> /dev/null ;
  fi;
   if [[ $? -eq "0" ]] ;
    then 
    echo -e "\nConfigs Restored from "$opt"\n" ;
    kquitapp5 plasmashell && kstart5 plasmashell </dev/null &>/dev/null &
    else
    echo -e "Something went wrong.\nAre you sure you have rights to access these folders?\n";
   fi;
 else
 echo -e "\n I dont know what to do";
 echo "$HELP";
 exit;
 fi;
 shift;; # restore from backup

 *)
 echo "$HELP";
 break
 ;;

esac

done

exit
